### PR TITLE
Fixes #761 | Updated Dockerfile and CONTRIBUTING docs

### LINKED ISSUE #761: [BUG] Docker build failing due to edge package being inaccessible
When running ```docker build -t feroxbuster:latest .``` I am running into apk errors.

**To Reproduce**
```
git clone https://github.com/epi052/feroxbuster.git
cd feroxbuster
docker build -t feroxbuster:latest .
```

**Expected behavior**
The docker build command completes successfully.

**Traceback / Error Output**
Docker build output
```
docker build -t feroxbuster:latest .
Sending build context to Docker daemon  37.12MB
Step 1/10 : FROM alpine@sha256:69704ef328d05a9f806b6b8502915e6a0a4faa4d72018dc42343f511490daf8a as build
 ---> 14119a10abf4
Step 2/10 : LABEL maintainer="wfnintr@null.net"
 ---> Using cache
 ---> 4c0b2a210083
Step 3/10 : RUN sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories     && apk upgrade --update-cache --available && apk add --update openssl
 ---> Running in 53d4023b00e1
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/edge/main: UNTRUSTED signature
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/edge/community: UNTRUSTED signature
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/community: No such file or directory
(1/3) Purging ssl_client (1.33.1-r3)
(2/3) Purging libretls (3.3.3p1-r2)
(3/3) Purging ca-certificates-bundle (20191127-r5)
Executing busybox-1.33.1-r3.trigger
OK: 5 MiB in 11 packages
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
140060314684232:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
ERROR: https://dl-cdn.alpinelinux.org/alpine/edge/main: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
140060314684232:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
ERROR: https://dl-cdn.alpinelinux.org/alpine/edge/community: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/community: No such file or directory
ERROR: unable to select packages:
  openssl (no such package):
    required by: world[openssl]
The command '/bin/sh -c sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories     && apk upgrade --update-cache --available && apk add --update openssl' returned a non-zero code: 1
```

**Environment (please complete the following information):**
 - feroxbuster version: latest as of 13/01/2023 
 - OS: Linux 5.19.0-21-generic #21-Ubuntu SMP PREEMPT_DYNAMIC Wed Oct 12 18:33:17 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
After removing the sed command, I am able to set up the container successfully.

```dockerfile
# FROM
RUN sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories \
    && apk upgrade --update-cache --available && apk add --update openssl
# TO
RUN  apk upgrade --update-cache --available && apk add --update openssl
```

LOGS:
```
docker build -t feroxbuster:latest .
Sending build context to Docker daemon  37.12MB
Step 1/10 : FROM alpine@sha256:69704ef328d05a9f806b6b8502915e6a0a4faa4d72018dc42343f511490daf8a as build
 ---> 14119a10abf4
Step 2/10 : LABEL maintainer="wfnintr@null.net"
 ---> Using cache
 ---> 4c0b2a210083
Step 3/10 : RUN apk upgrade --update-cache --available && apk add --update openssl
 ---> Using cache
 ---> d44a524da6fa
Step 4/10 : RUN wget https://github.com/epi052/feroxbuster/releases/latest/download/x86_64-linux-feroxbuster.zip -qO feroxbuster.zip     && unzip -d /tmp/ feroxbuster.zip feroxbuster     && chmod +x /tmp/feroxbuster     && wget https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/Web-Content/raft-medium-directories.txt -O /tmp/raft-medium-directories.txt
 ---> Using cache
 ---> e414000c8506
Step 5/10 : FROM alpine@sha256:69704ef328d05a9f806b6b8502915e6a0a4faa4d72018dc42343f511490daf8a as release
 ---> 14119a10abf4
Step 6/10 : COPY --from=build /tmp/raft-medium-directories.txt /usr/share/seclists/Discovery/Web-Content/raft-medium-directories.txt
 ---> Using cache
 ---> 8aafc373fc61
Step 7/10 : COPY --from=build /tmp/feroxbuster /usr/local/bin/feroxbuster
 ---> Using cache
 ---> a807378285d0
Step 8/10 : RUN adduser     --gecos ""     --disabled-password     feroxbuster
 ---> Using cache
 ---> 24fad7e2f7bf
Step 9/10 : USER feroxbuster
 ---> Using cache
 ---> d96825da87ff
Step 10/10 : ENTRYPOINT ["feroxbuster"]
 ---> Using cache
 ---> f60e8c081db0
Successfully built f60e8c081db0
Successfully tagged feroxbuster:latest
```

I have submitted a PR to fix this.
Let me know if you need anything else.

### PR DESCRIPTION
**Pull request by aidanhall34**
# Landing a Pull Request (PR)
Fixes #761
My first public PR, be gentle if I have managed to screw this up😄 

Long form explanations of most of the items below can be found in the [CONTRIBUTING](https://github.com/epi052/feroxbuster/blob/master/CONTRIBUTING.md) guide.

## Branching checklist
- [x] There is an issue associated with your PR (bug, feature, etc.. if not, create one)
- [x] Your PR description references the associated issue (i.e. fixes #123456)
- [x] Code is in its own branch
- [x] Branch name is related to the PR contents
- [x] PR targets main

## Static analysis checks
- [ ] All rust files are formatted using `cargo fmt`
- [ ] All `clippy` checks pass when running `cargo clippy --all-targets --all-features -- -D warnings -A clippy::mutex-atomic`
- [ ] All existing tests pass

## Documentation
- [x] New code is documented using [doc comments](https://doc.rust-lang.org/stable/rust-by-example/meta/doc.html)
- [x] Documentation about your PR is included in the `docs`, as needed. The docs live in a [separate repository](https://epi052.github.io/feroxbuster-docs/docs/). Update the appropriate pages at the links below.
  - [ ] update [example config file section](https://epi052.github.io/feroxbuster-docs/docs/configuration/ferox-config-toml/)
  - [ ] update [help output section](https://epi052.github.io/feroxbuster-docs/docs/configuration/command-line/)
  - [ ] add an [example](https://epi052.github.io/feroxbuster-docs/docs/examples/)
  - [ ] update [comparison table](https://epi052.github.io/feroxbuster-docs/docs/compare/)

## Additional Tests
- [ ] New code is unit tested
- [ ] New code is integration tested, as needed
- [ ] New tests pass

### CODE REVIEW

**Comment by aidanhall34** [comment]
Thought I would find and replace all refs to "master" to main in CONTRIBUTING.md as that's the name of the master branch.

If there is more testing/anything I should have done before pushing this up let me know. Very happy to learn about how to do public PR's the right way.

Thanks!

**Comment by epi052** [comment]
ayyyyy, congrats on your first PR 🥳 

thank you for updating the contributing file, that's been around since before the master->main transfer and (obviously) got overlooked, ty! 

the  original docker stuff was submitted through a PR, so I'm not super familiar with it. Any idea what was making it fail, or why removing the sed fixes things?

**Comment by aidanhall34** [comment]
There is an issue with the edge builds signature in the container. I have cated out the repo list before and after the sed:
```dockerfile
...
RUN printf "Original\n"; cat /etc/apk/repositories && \
    sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories && \
    printf 'Updated\n'; cat /etc/apk/repositories && \
    apk upgrade --update-cache --available && apk add --update openssl
...
```
Here is the output from that section of the build:
```
Step 3/10 : RUN printf "Original\n"; cat /etc/apk/repositories &&     sed -i -e 's/v[[:digit:]]\..*\//edge\//g' /etc/apk/repositories &&     printf 'Updated\n'; cat /etc/apk/repositories &&     apk upgrade --update-cache --available && apk add --update openssl
 ---> Running in eca7b5a2d72b
Original
https://dl-cdn.alpinelinux.org/alpine/v3.14/main
https://dl-cdn.alpinelinux.org/alpine/v3.14/community
Updated
https://dl-cdn.alpinelinux.org/alpine/edge/main
https://dl-cdn.alpinelinux.org/alpine/edge/community
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/edge/main: UNTRUSTED signature
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/edge/community: UNTRUSTED signature
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/community: No such file or directory
(1/3) Purging ssl_client (1.33.1-r3)
(2/3) Purging libretls (3.3.3p1-r2)
(3/3) Purging ca-certificates-bundle (20191127-r5)
Executing busybox-1.33.1-r3.trigger
OK: 5 MiB in 11 packages
fetch https://dl-cdn.alpinelinux.org/alpine/edge/main/x86_64/APKINDEX.tar.gz
140145411455816:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
ERROR: https://dl-cdn.alpinelinux.org/alpine/edge/main: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/main: No such file or directory
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
140145411455816:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1914:
ERROR: https://dl-cdn.alpinelinux.org/alpine/edge/community: Permission denied
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/edge/community: No such file or directory
ERROR: unable to select packages:
  openssl (no such package):
    required by: world[openssl]
```

This UNTRUSTED signature error is due to the container version not having the right keys to use the edge installs.
Removing the sed keeps it on the community and main branches which makes it happy again.

There are a few possible solutions I can think of:
a) Remove the sed and use the "main" and "community" branches (current solution)
b) Upgrade alpine to a later version. Moving it to alpine:3.17.1 allows us to continue using the "edge branch"
c) Upgrade the container version and remove sed. This keeps it up to date and ensures we are only pulling stable openssl updates
d) Append ```--allow-untrusted``` to the end of the apk commands. I feel this is an ugly bandaid but resolves the issue.


I have built and tested all of the solutions. They allow the build process to complete and I am able to start feroxbuster in the container.

**Comment by epi052** [comment]
tbh, i don't know why we were using edge in the first place. So, I'm willing to accept whatever solution you think is the best solution moving forward.

**Comment by aidanhall34** [comment]
I think in this case option C would be best. 3.14 is almost EOL anyway so might as well migrate.
https://endoflife.date/alpine

**Comment by epi052** [comment]
sounds good! tysm for taking the time to work through this and congrats again on your first PR!

@all-contributors add @aidanhall34 for code and infra

**Pull request merged**
