### PR TITLE
Adding feroxbuster as chocolatey package

### PR DESCRIPTION
**Pull request by aancw**
Fixes https://github.com/epi052/feroxbuster/issues/763

push the package to chocolatey using your API credential as explained in this page https://docs.chocolatey.org/en-us/create/create-packages-quick-start

Push the package to the Chocolatey community package repository:

- Get a Chocolatey account:
- [Register](https://chocolatey.org/account/register)
- Copy the API key from [your Chocolatey account](https://chocolatey.org/account).
```
choco apikey --api-key [API_KEY_HERE] -source https://push.chocolatey.org/
choco push package-name.1.1.0.nupkg --source https://push.chocolatey.org/ - nupkg file can be omitted if it is the only one in the directory.
```

So, every release of feroxbuster need to be pushed on chocolatey too. I think this can be automated using github workflow.

# Landing a Pull Request (PR)

Long form explanations of most of the items below can be found in the [CONTRIBUTING](https://github.com/epi052/feroxbuster/blob/master/CONTRIBUTING.md) guide.

## Branching checklist
- [x] There is an issue associated with your PR (bug, feature, etc.. if not, create one)
- [x] Your PR description references the associated issue (i.e. fixes #123456)
- [x] Code is in its own branch
- [x] Branch name is related to the PR contents
- [ ] PR targets main

## Static analysis checks
- [ ] All rust files are formatted using `cargo fmt`
- [ ] All `clippy` checks pass when running `cargo clippy --all-targets --all-features -- -D warnings -A clippy::mutex-atomic`
- [ ] All existing tests pass

## Documentation
- [ ] New code is documented using [doc comments](https://doc.rust-lang.org/stable/rust-by-example/meta/doc.html)
- [ ] Documentation about your PR is included in the `docs`, as needed. The docs live in a [separate repository](https://epi052.github.io/feroxbuster-docs/docs/). Update the appropriate pages at the links below.
  - [ ] update [example config file section](https://epi052.github.io/feroxbuster-docs/docs/configuration/ferox-config-toml/)
  - [ ] update [help output section](https://epi052.github.io/feroxbuster-docs/docs/configuration/command-line/)
  - [ ] add an [example](https://epi052.github.io/feroxbuster-docs/docs/examples/)
  - [ ] update [comparison table](https://epi052.github.io/feroxbuster-docs/docs/compare/)

## Additional Tests
- [ ] New code is unit tested
- [ ] New code is integration tested, as needed
- [ ] New tests pass

### CODE REVIEW

**Comment by aancw** [comment]
Hey, I think you need to update the license file for copyright year. It's still 2020. Maybe 2020-2023 is more suitable.

**Comment by epi052** [comment]
yea, the range would be fine. ty! 

I read through the xml and it all looks good. 

are the checksums in the install package a manual process? i.e. do they need manually updated with each release?

any thoughts on this? https://github.com/marketplace/actions/chocolatey-action (or a similar action?)

**Comment by aancw** [comment]
I think the checksum is manual input. It can be automatic like editing the xml file with python everytime the release exist. 

It's good idea to use that github action for doing choco api key and choco push. I've not yet try, but it looks good.

**Comment by epi052** [comment]
> Note:
> 
> Need to make the icon from logo and we can change the value in this xml
> 
> ```
>     
> ```

I never thanked you for putting this PR in... sorry! and thank you for taking the time on this one (as well as the menu/banner PR), i really do appreciate it!

i saw that while reading through. been pushing this one off in favor of your other PR and one that I'm working, since it's not anything that will affect other branches. once i get those two in (probably today), i'll be able to work on this one

**Comment by epi052** [comment]
isolated-layout

**Comment by epi052** [comment]
derp

**Comment by epi052** [comment]
```
https://rawcdn.githack.com/epi052/feroxbuster/2d381e7e057ce60c580b324dd36c9abaf30c2ec7/img/logo/logo.png
```

**Comment by aancw** [comment]
Thank you for your appreciation, I'm so honored to contribute this project. I will push the commit for new logo soon.

**Comment by epi052** [comment]
pushed 2.8.0 as part of testing this, all seemed to work. they say it goes through automated tasks and will eventually be available. I'll look into automating this some other time. for now, i'm ok with it just being a manual process

**Comment by epi052** [comment]
thanks again for all your help!

**Comment by aancw** [comment]
Note: The checksum value in xml need to be updated with the latest version

**Pull request merged**
