### PR TITLE
Enable reading extensions from file

### LINKED ISSUE #925: [FEATURE REQUEST] Support reading extension list from a file
Currently -x accepts extensions list only as a string. Therefore I have to do something like this:
`-x $(cat ext.txt)`
to avoid retyping my extension list every time. It would be convenient to read them from file directly. If user specified valid file path as -x parameter value 😄

### PR DESCRIPTION
**Pull request by andreademurtas**
closes #925

### CODE REVIEW

**Comment by epi052** [comment]
hey there, thank you for taking the time to put this together! I'll be able to review it this weekend

**Review by epi052 — CHANGES_REQUESTED** [review]
just a few small suggestions, mostly code preference/cleanup. Once these are done, we can get it merged. Thanks again!

**Comment by andreademurtas** [comment]
Should be done!

**Comment by epi052** [comment]
looks good! i'll hit the fmt/clippy stuff after merge, don't worry about that. thanks for putting this together!

@all-contributors add @andreademurtas for code

**Pull request merged**
