### PR TITLE
Publish to Arch User Repository

### PR DESCRIPTION
**Pull request by spikecodes**
Hi, I love Feroxbuster and wanted to help more users access it so as an Arch Linux user, I [published it to the AUR](https://aur.archlinux.org/packages/feroxbuster/) (Arch User Repository) under the package name `feroxbuster`.

This pull requests just appends to the installation instructions of the README.md telling users how they can install it from Arch Linux.

Thank you for making an awesome project! If you have an AUR account and would like me to transfer ownership of the package to you, I'd be happy to do that as well.

### CODE REVIEW

**Comment by epi052** [comment]
Thank you for the submission, this is great!

I have a few questions, as I'm unfamiliar with Arch and AUR (I don't use Arch btw :wink:).  

It looks like git and cargo are dependencies, which to me implies that when a user runs `yay -S feroxbuster`, the package manager clones the repo and builds from source using `cargo`.  Is that accurate?  

Is there any config file / metadata specification file tied to the published package, if so, is it publicly visible anywhere?  

I guess my questions boil down to, is this kept in sync with the latest release and does anything except git clone / cargo build happen underneath the hood?

**Comment by epi052** [comment]
Follow up question, is there a way to track installs from AUR?  If so, can you check for a badge on shields.io for it?

**Comment by spikecodes** [comment]
Good questions!

> It looks like git and cargo are dependencies, which to me implies that when a user runs `yay -S feroxbuster`, the package manager clones the repo and builds from source using `cargo`. Is that accurate?

Yes this is accurate. After cloning and building using `cargo build --release`, it installs the binary in `/usr/bin/` so that Arch users can run feroxbuster from the command line.

> Is there any config file / metadata specification file tied to the published package

Yes! The Arch User Repository uses a specification called PKGBUILD and you can see the specification for it [here](https://wiki.archlinux.org/index.php/PKGBUILD). PKGBUILDs are a set of instructions telling user's computers how to find, build and install a project. 

> Is it publicly visible anywhere?

Yep! You can see `feroxbuster`'s PKGBUILD file [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=feroxbuster). This one is quite simple and hopefully each part should make sense. The `build()` function is run first which executes `cargo build --release` under the hood and then following the AUR specification installs it to the user computer in the `package()` function.

> I guess my questions boil down to, is this kept in sync with the latest release

Yes this will install directly from the most recent commit. 

> does anything except git clone / cargo build happen underneath the hood?

Nope, that's really it.

> Follow up question, is there a way to track installs from AUR? If so, can you check for a badge on shields.io for it and add it to the readme ?

Hmm I'm not sure if you can track the number of installs but you can view the "Popularity" and "Votes" field on the [package page](https://aur.archlinux.org/packages/feroxbuster/). Shields.io does have a badge for the "votes":
AUR votes

Should I add that to the README?

**Comment by spikecodes** [comment]
> Is this kept in sync with the latest release?
To add, for it to reinstall the code and tell users an update is available, I'd have to update the package version.

**Comment by epi052** [comment]
> > Is this kept in sync with the latest release?
> 
> To add, for it to reinstall the code and tell users an update is available, I'd have to update the package version so it matches the most recent release version.

haha, was just about to ask how `pkgver=1.0.5` comes into play.

**Comment by spikecodes** [comment]
Actually, I'll include a `pkgver()` function like the one below which should register an update whenever a commit is made meaning the AUR package maintainer can just set it and forget it (I won't have to change the pacakge version each time a commit/release is made).
```bash
pkgver() {
	cd "${_pkgname}"
	( set -o pipefail
		git describe --long 2>/dev/null | sed 's/\([^-]*-g\)/r\1/;s/-/./g' ||
		printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
	)
}
```

**Comment by epi052** [comment]
`git describe --tags | awk -F- '{print $1}' | cut -c2-` appears to work

**Comment by spikecodes** [comment]
Thanks, that looks good! Though that will be in sync with tags rather than commits, is this what you are going for? Would you like me to make a second Arch package for `feroxbuster-git` (`-git` is standard for AUR packages that sync to Git commits) which would be in sync with commits rather than tags? I'd be happy to do this and this would give users both a stable and bleeding edge option.

**Comment by epi052** [comment]
brb, but tldr is that master is always in sync with tags as far as the binary itself is concerned

**Comment by epi052** [comment]
well, I'm back much quicker than i thought... lol.  

so, i work in branches and only merge to master when complete.  after merge i publish a new release.  The release tags will always be in the `vX.X.X` format. The only time that master is out of sync with the latest tagged commit is when the readme / CI config / etc is updated.  Anything that affects the binary will be captured in a tagged commit.

**Comment by epi052** [comment]
As far as the readme badge, don't sweat it.  If one were available for installs, I'd like it, but it's ok that there's not.

**Comment by spikecodes** [comment]
Gotcha, yeah that all makes sense. Alright I've updated the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=feroxbuster) so `feroxbuster` on the AUR is now in sync with tagged commits.

**Comment by epi052** [comment]
Is it ok to have both a static pkgver and a pkgver function defined?

**Comment by spikecodes** [comment]
Yeah, the `pkver()` function will always override the `pkgver` variable.

**Comment by spikecodes** [comment]
Also, the function actually self-edits (updates) the variable.
image

**Comment by epi052** [comment]
Good stuff!  Thanks for this PR, and thanks for checking out the tool.  Merging! :partying_face:

**Comment by spikecodes** [comment]
Awesome, thanks! 🙂 Keep up the great work with feroxbuster!

**Pull request merged**
