### PR TITLE
134 cargo git cli docs

### PR DESCRIPTION
**Pull request by mzpqnxow**
This is just documentation. It's not worded particularly well, nor is it structured very well. Please feel free to reject/close it and it can be here searchable if anyone has the same issue, or just modify it before accepting it (or suggest a change and I'll make it)

### CODE REVIEW

**Comment by mzpqnxow** [comment]
If anyone is searching on the error, it is `Failed to retrieve list of SSH authentication methods: Failed getting response; class=Ssh`

**Comment by epi052** [comment]
Thanks for this!  Just wanted to let you know I see it and will review it once i get #124 merged in.

**Comment by epi052** [comment]
Unfortunately, I don't see a need for this particular entry in the README. We don't discuss building from source anywhere in the README right now (purposefully, as I'd prefer to handle the entire build life-cycle myself). Additionally, my release strategy doesn't include a nightly/dev/experimental build; I keep master in sync with each release.  

I think there's value in having this problem/solution indexed, but I don't think it needs an entry in the docs.  I'm willing to have my mind changed, but those are my current thoughts on the subject.  Closing for now, but feel free to add discussion/reopen if necessary.

**Comment by mzpqnxow** [comment]
No worries, I agree it's not essential and really, it's probably not a great idea to be in the business of offering support to users who don't know what they're doing, trying to build from source when packages are readily available and installing when is well documented

**Pull request closed without merging**
