### PR TITLE
Publish with Homebrew on MacOS & Linux 🍺

### PR DESCRIPTION
**Pull request by TGotwig**

### CODE REVIEW

**Comment by epi052** [comment]
i won't be able to review until after work, but thank you again!

**Comment by TGotwig** [comment]
Gladly 😊

**Comment by epi052** [comment]
I took a look at the PR and the associated repos.  I have a few questions:

1. why is the ruby hosted in a different repo?
2. why is the binary re-compiled and then hosted?  i.e. why doesn't the download point to this repo's release? 
3. can the final url point to `.../releases/latest/download/...` instead of needing to update with every release?

I spun up a vm and installed homebrew on linux and everything worked.  The feroxbuster install was seamless once I got homebrew installed, which is awesome. However, I'm not entirely keen on relying on another repo for the hosting.  Unless there's a homebrew reason that I'm unaware of, I'd rather see everything self-contained here, even if it means tweaking the CI/CD to accommodate.  

Looking forward to your response, and thanks again!

**Comment by TGotwig** [comment]
1. It's a convention that the repos which contain a 3rd party formula must start with `homebrew-` / `homebrew-linux-` in their name.
2. Because it requires `tar.gz` archives and in your releases are only `zip` ones, when you upload such archives I can point to them. 🙂
3. I guess you mean the `url`-line of the formula, it is required to specify a version inside the formula, when not specified in the url then otherwise with an extra line like `version "1.0.1"`, the official brew-formulas require this to be in the url, otherwise their tests fail.

Hmmm so in that case, maybe it would be the best when I give you `ownership` to these two Homebrew repos and update my commit appropriately? 🍺

**Comment by epi052** [comment]
Ok, I assumed it was just my unfamiliarity with homebrew and its deployment conventions.  

I don't think we need to do an ownership swap. However, can you confirm that this would be the steps to update going forward?
1. tag a new release in `epi052/feroxbuster` / upload new binaries to the tagged release
2. submit a PR to `TGotwig/homebrew-linux-feroxbuster` with updated version and hash
3. submit a PR to `TGotwig/homebrew-feroxbuster` with updated version and hash

As far as the URL, if we have to bump the version with each release, it probably doesn't matter if it's in the URL itself or a `version` attribute.

I should have my CI spitting out a `.tar.gz` here shortly.  I expect the URL to be 

`https://github.com/epi052/feroxbuster/releases/download/v1.0.2/x86_64-macos-feroxbuster.tar.gz`

Could we update the formulae to point here for the download url?

**Comment by TGotwig** [comment]
Yeah mostly right 😃 you just have to update the version inside the url, the hash must be generated by an 256 algorithm, you can generate it by `shasum -a 256 <FILE>`.

I think it's better to have the version just inside the url because that makes the code shorter and is the recommended way 😇

I think you should be able to directly commit into `master` when I invite you, easier than opening a PR 🙂

Successfully updated the url and the hash 👍✨

**Comment by epi052** [comment]
Awesome! I got the invites and will update the linux repo with a new url/hash once i get a tar.gz integrated into the CI/CD for linux.  

Merging this branch, as the remaining work is elsewhere.  Thanks again!

**Comment by TGotwig** [comment]
@epi052 Maybe you can give this the label `hacktoberfest-accepted `? 🙂

**Comment by epi052** [comment]
fo sho, incoming :partying_face:

the repo has `hacktoberfest`, but it may not have been on there for yours.

**Comment by epi052** [comment]
If that doesn't show up in your hacktoberfest tracker, let me know and we can get it sorted

**Comment by TGotwig** [comment]
Well, it does show up, but somehow it has still the status `In Review`, although all of my 4 PRs were merged 😅 Maybe the label will fix this 🤔🧪

**Comment by TGotwig** [comment]
Seems to work 👍 Just have to wait until the countdown hits zero 😅😊🤘

**Pull request merged**
